const project = [
  {
  title: "Movie App",
  github: "https://github.com/ChuloCr8v/proflix",
  demo: "https://proflix.vercel.app/",
  img: '/prof.jpg',
  description: "Proflix is a movie database app that can be used to get information about movies including their release date, average ratings and trailer. Movies were fetched from TheMovieDatabase.",
  stackOne: "Html5",
  stackTwo: "Sass",
  stackThree: "Css3",
  stackFour: "React-redux-toolkit",
  featureOne: "Contains different genre of movies",
  featureTwo: "Movie Trailers and Details about specific movies",
  featureThree: "Responsive design across all devices",
  featureFour: "Sleek Design"
},
  {
    title: 'Grampro Photobucket',
    img: '/grampro.jpg',
    github: "https://github.com/ChuloCr8v/grampro",
    demo: "https://grampro.netlify.app",
    stackOne: "Html5",
    stackTwo: "Sass",
    stackThree: "Css3",
    stackFour: "Google Firebase/Firestore",
    description: "This is a Photo Bucket that allows uploading of pictures and preview of uploaded pictures. The uploaded pictures are stored with Google Firebase which acts as the backend.",
    featureOne: "Allows upload and preview of uploaded pictures.",
    featureTwo: "Users can only upload and preview uploads.",
    featureThree: "Mobile Responsiveness",
    featureFour: "Spots a sleek design.",
  },
 /* {
    title: 'Crypto Wallstreet',
    img: '/crypto.jpg',
    github: "https://github.com/ChuloCr8v/cryptowallstreet",
    demo: "https://cryptowallstreet.vercel.app",
    description: "This is a web app designed to provide current information on cryptocurrencies. You can view different cryptocurrency details, their market standings as well as their price chart. You can as well view the history of each cryptocurrency. It also contains a list of exchanges and their brief introduction.",
    stackOne: "Html5",
    stackTwo: "Sass",
    stackThree: "Css3",
    stackFour: "React-redux",
    featureOne: "Displays vital information on cryptocurrencies.",
    featureTwo: "Chart.js for displaying crypto price chart",
    featureThree: "Top cryptocurrency news update.",
    featureFour: "Mobile Responsive.",
  },
  */
  {
    title: 'Big Shotz Photography',
    img: '/big.jpg',
    github: "https://github.com/ChuloCr8v/Bigshotz",
    demo: "https://bigshotz.vercel.app",
    description: "This is a photography portfolio website designed to showcase the profile of a photographer. It contains details about the photographer such as skills, services, picture gallery and contact details. Images were fetched from unsplash api. It also includes a search bar where you can search for different images.",
    stackOne: "Html5",
    stackTwo: "Css3",
    stackThree: "Next.js",
    featureOne: "Contains different sections including hero, contact, work tools and pictures gallery.",
    featureTwo: "Contains different pictures categories including nature, wedding, people and random images.",
    featureThree: "Visitors can search for random pictures with the search bar included in the random pictures page.",
    featureFour: "Mobile Responsive.",
  },
  {
    title: 'uknight template',
    demo: 'https://uknight.netlify.app',
    img: '/uknite.png', 
    description: "This is a website template with a sleek design and important sections for startups and businesses alike.",
    stackOne: "Html5",
    stackTwo: "Css3",
    stackThree: "JavaScript",
    featureOne: "Contains different sections including hero, features, about us, call to action section etc.",
    featureTwo: "Spots an amazing design.",
    featureThree: "Features a responsive menu.",
    featureFour: "Mobile Responsive.", 
    
  },
  {
    title: 'Unox template',
    demo: 'https://unox.netlify.app',
    img: '/unox.png', 
     description: "This is a website template with a sleek design and important sections for startups and businesses alike.",
    stackOne: "Html5",
    stackTwo: "Css3",
    stackThree: "JavaScript",
    featureOne: "Contains different sections including hero, features, about us, call to action section etc.",
    featureTwo: "Spots an amazing design.",
    featureThree: "Features a responsive menu.",
    featureFour: "Mobile Responsive.", 
     
  },
  {
    title: 'Dauxo template',
    demo: 'https://dauxo.netlify.app',
    img: '/project1.jpg', 
     description: "This is a website template with a sleek design and important sections for startups and businesses alike.",
    stackOne: "Html5",
    stackTwo: "Css3",
    stackThree: "JavaScript",
    featureOne: "Contains different sections including hero, features, about us, call to action section etc.",
    featureTwo: "Spots an amazing design.",
    featureThree: "Features a responsive menu.",
    featureFour: "Mobile Responsive.", 
    
  },
]

export default project